CHANNEL_NUM = 3
SIZE = 256
CLEAN_DIR = './samples/clean'
NOISY_DIR = './samples/noisy'
CLEAN_VAL_DIR = './samples/clean/validation'
NOISY_VAL_DIR = './samples/noisy/validation'
DDPM_DENOISED_DIR = 'samples/ddpm-denoised'
MPRNET_DENOISED_DIR = 'samples/mprnet-denoised'
MODEL = 'lsun_church'
DEVICE = 'cuda:0'
# DEVICE = 'cpu'
SAVE_NOISY = True  # True when saving noisy images, False when denoising
GAUSSIAN_NOISE = True  # True if noises are Gaussian-distributed, False if Gaussian-Poisson
LEVELS = [.05, .1, .2, .4]
LAMBDA = .01
